name: Bug Report
description: 给启动器本身提交 Bug 报告。
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出宝贵时间填写此错误报告！ 请仔细阅读此页面上的所有提示，并确保您在**提交前**输入了相关详细信息。
  - type: checkboxes
    id: terms
    attributes:
      label: 更新免责声明
      description: 如果 FFXIV 最近刚刚更新，XIVLauncher 和插件将无法工作。他们需要随之更新。您可以前往QQ频道获取有关更新的通知。
      options:
        - label: 是的，我已经检查过了，我的问题与 FFXIV 更新和插件无法正常工作无关。
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 您做了什么？
      description: 问题发生时您在做什么？ 请给我们*一步一步*的指示。 您可以将日志文件和截图图像拖放到此处来添加附件。
      placeholder: 告诉我们您的操作步骤！
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 平台
      description: 您在哪种平台运行 XIVLauncher?
      options:
        - Windows
        - Linux (Wine/Proton)
        - Linux (native)
        - Mac OS X
    validations:
      required: true
  - type: input
    id: runnerver
    attributes:
      label: Wine/Proton 运行版本
      description: 如果您使用的是 Linux 或 Mac OS X，您使用的是哪个版本的 Wine/Proton？ 如果您使用的是 Windows，请将其留空。
      placeholder: 例如 Proton-GE-7.0
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关日志文件
      description: 请复制并粘贴任何相关的日志输出或错误消息。 您可以在弹出的错误消息或相关日志文件中看到这些。
      render: shell
