blank_issues_enabled: true
contact_links:
  - name: XIVLauncher CN FAQ
    url: https://ottercorp.github.io/faq/
    about: 有关 XIVLauncher CN 和您可能遇到的潜在问题的帮助和更多信息。请在提问前先检查一下。
  - name: XIVLauncher CN QQ频道
    url: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&inviteCode=CZtWN&from=181074&biz=ka&shareSource=5
    about: 关于 XIVLauncher CN 及其开发的讨论 - 如果您在常见问题解答中找不到答案，我们将尽力回答您的问题！
